version: '3'
services:
  prisma:
    container_name: full-js
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4469:4469"
    environment:
      PRISMA_CONFIG: |
        port: 4469
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    container_name: full-js-db
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data2
  pgadmin:
    container_name: full-js-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: prisma
      PGADMIN_DEFAULT_PASSWORD: prisma
      # PGADMIN_ENABLE_TLS: 1
    ports:
    - "5000:80"
      # TLS
      # - "${PGADMIN_PORT:-5443}:8443"
volumes:
  postgres: ~
